name: recipe_app
description: A Flutter recipe sharing app

publish_to: 'none' # Remove this line if you intend to publish your package

environment:
  sdk: '^3.8.0' # Keep this as is or update to your actual SDK version

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.3
  image_picker: ^1.1.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true